# Generated by Django 5.2.4 on 2025-07-20 19:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_aboutimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Upload a video file (e.g., MP4)', max_length=255, null=True, verbose_name='video'),
        ),
    ]
