# Generated by Django 5.2.4 on 2025-07-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_aboutimage_image_alter_collection_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, help_text='Upload a video file (e.g., MP4)', null=True, upload_to='testimonials/'),
        ),
    ]
